name: NavyCraft
main: com.maximuspayne.navycraft.NavyCraft
version: 1.0.1
authors: [Yogoda, SycoPrime, Maximuspayne, NavalClash Dev team]
depend: [AimCannonNC,WorldGuard,WorldEdit,Essentials,GroupManager]
NavalClash.net modified 4/6/17


commands:
   navycraft:
      description: Ship and other vehicle based commands
      usage:
           /<command>
   ship:
      description: Ship
   aircraft:
      description: Aircraft
   submarine:
      description: Submarine
